#!/bin/bash
# Module: deploy_status — records start/finish timestamps per deploy mode.
# Plug-and-play: source in deploy.sh module block; add 2 call sites (marked below).
# To remove: delete this file + remove its source line + remove the 2 call sites.

DEPLOY_STATUS_FILE="$PROJECT_ROOT/scripts/deploy_status.md"

_DEPLOY_STATUS_MODES=("full" "--dags-only" "--provision" "--snowflake-setup" "--fix-ml-venv" "--bake-ami")

# Determine mode from flags set by deploy.sh argument parsing
_deploy_status_mode() {
    if   [ "${DAGS_ONLY:-false}"       = true ]; then echo "--dags-only"
    elif [ "${PROVISION:-false}"       = true ]; then echo "--provision"
    elif [ "${SNOWFLAKE_SETUP:-false}" = true ]; then echo "--snowflake-setup"
    elif [ "${FIX_ML_VENV:-false}"    = true ]; then echo "--fix-ml-venv"
    elif [ "${BAKE_AMI:-false}"       = true ]; then echo "--bake-ami"
    else echo "full"
    fi
}

# Create the file from scratch with all sections set to "(none yet)"
_deploy_status_init() {
    {
        printf "Deploy Status  (auto-generated by ./scripts/deploy.sh — do not edit)\n\n"
        for _ds_mode in "${_DEPLOY_STATUS_MODES[@]}"; do
            printf "[%s]\n  Last Deploy Started:  (none yet)\n  Last Clean Finish:    (none yet)\n\n" "$_ds_mode"
        done
    } > "$DEPLOY_STATUS_FILE"
}

# Update one field in the file using awk (section-aware, writes via tmp file)
_deploy_status_set() {
    local mode="$1" label="$2" value="$3"
    local tmp="${DEPLOY_STATUS_FILE}.tmp"
    awk -v sec="[$mode]" -v lbl="$label" -v val="$value" '
        /^\[/ { in_sec = ($0 == sec) }
        in_sec && index($0, lbl) == 1 { sub(/:[[:space:]]+.*/, ":  " val); in_sec=0 }
        { print }
    ' "$DEPLOY_STATUS_FILE" > "$tmp" && mv "$tmp" "$DEPLOY_STATUS_FILE"
}

# CALL SITE 1 — called from deploy.sh after argument parsing
_deploy_status_write_started() {
    [ -f "$DEPLOY_STATUS_FILE" ] || _deploy_status_init
    _deploy_status_set "$(_deploy_status_mode)" "  Last Deploy Started" "$(date '+%Y-%m-%d %H:%M:%S')"
}

# CALL SITE 2 — called from _print_deploy_summary in common.sh (clean-exit branch only)
_deploy_status_write_clean() {
    [ -f "$DEPLOY_STATUS_FILE" ] || return
    _deploy_status_set "$(_deploy_status_mode)" "  Last Clean Finish" "$(date '+%Y-%m-%d %H:%M:%S')"
}
